refactor: Replace `consola` with `pino`
better-auth/better-auth pull request #440
Opened 2024-11-06 22:35 UTC by tklein1801

So far, the options for customizing in logging are very limited or only log-level and activation can be set. It should be discussed which aspects of the logger should be configurable by the user

2024-11-06 22:36 UTC, tklein1801 commented
#124

2024-11-12 20:14 UTC, tklein1801 commented
@Bekacru just resolved the merge conflict. Do you mind running the CI again?

2024-11-12 21:03 UTC, Bekacru commented
Sure. Also please remove pkg-lock.json and the pnpm lock file too. And remove any new deps since we're not using them.

2024-11-12 21:16 UTC, tklein1801 commented
Sure. Done.

2024-11-12 21:43 UTC, tklein1801 commented
Sure. Should be it.

2024-11-13 15:12 UTC, Bekacru commented
My current concern is that this will remove the nice greenish success message in the CLI for migrate and generate. Maybe we could have the CLI use the consola logger directly instead, since it can't be configured. If you could make this change, this would be good to go!

2024-11-13 16:01 UTC, tklein1801 commented
Sure, let me look at that. Currently, however, Consola should already be used because, as you wrote, an unconfigured logger is configured from better-auth and therefore the standard handler (Consola) is used.

I will check the behavior again and make changes if necessary.

2024-11-13 16:05 UTC, Bekacru requested changes

2024-11-13 16:05 UTC, Bekacru commented on packages/cli/src/commands/generate.ts
> +		logger.info(`🚀 Schema was generated successfully!`);
Here it should be `success` instead

2024-11-13 16:05 UTC, Bekacru commented on packages/cli/src/commands/generate.ts
> -			logger.success(
same here

2024-11-13 16:05 UTC, Bekacru commented on packages/cli/src/commands/generate.ts
> +	logger.info(`🚀 Schema was generated successfully!`);
here

2024-11-13 16:05 UTC, Bekacru commented on packages/cli/src/commands/migrate.ts
> +	logger.info("🚀 migration was completed successfully!");
here as well

2024-11-13 16:05 UTC, Bekacru commented on packages/cli/src/utils/get-config.ts
> -							logger.break();
you can change this to just empty `console.log("")` instead

2024-11-13 17:48 UTC, tklein1801 commented
Sorry, I misunderstood you. How about the following solution?
We reintroduce the log level `success` for Consolas to make it possible to output successful messages, but if a custom logger is implemented, success is replaced by info as the log level, as success does not technically exist as a log level.

2024-11-13 18:10 UTC, tklein1801 commented
I made a mistake with the log-Level the get-config.ts file inside the cli Package. 

Will fix later

2024-11-13 21:38 UTC, tklein1801 commented
Done. Everything should be set now

2024-11-15 13:11 UTC, Bekacru commented
hey @tklein1801 please update the snapshot

2024-11-15 14:58 UTC, tklein1801 commented
Hi @Bekacru, I've already done this. I am still looking at the other two failed tests

2024-11-15 15:43 UTC, tklein1801 commented
**Test `oauth.test.ts` `oauth2 - should handle server error during OAuth flow`**

Runs into `cookie-utils.ts` and stopps right here

I think if the process cannot continue due to an error, an error should be thrown.
```ts
if (!name || value === undefined) {
  console.warn(`Malformed cookie: ${cookieString}`);
  return;
}
```

2024-11-16 15:47 UTC, tklein1801 commented
Well, I'll be honest... It took me a while to work out where the error was. 
Build and test are succeeding in local...

2024-11-18 06:58 UTC, merged