Update svetekit integrations docs update
better-auth/better-auth pull request #627
Opened 2024-11-23 08:30 UTC by nalonix

here's the update to the docs.

2024-11-23 14:15 UTC, Devr-pro requested changes

2024-11-23 14:15 UTC, Devr-pro commented on docs/content/docs/integrations/svelte-kit.mdx
> +      <button on:click={async () => await authClient.signOut()}>
should be onclick={} instead of on:click={}

2024-11-23 14:15 UTC, Devr-pro commented on docs/content/docs/integrations/svelte-kit.mdx
> +      on:click={async () => {
on:click -> onclick

2024-11-28 16:40 UTC, kaysef commented on docs/content/docs/integrations/svelte-kit.mdx
> +            session: Session | undefined;
why not 
```ts
session: import("$lib/auth").$Infer.Session['session'] | undefined | null;
```
Based on [this section of the docs](https://www.better-auth.com/docs/concepts/typescript#inferring-types). It also ensures every configurations done to the `auth` instance is captured in the type

2025-01-12 07:50 UTC, closed without merging